name: Sphynx Documentation

# Build for pushes to master and new tags
on:
  push:
    branches: [ master ]
    tags:
    - '*'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Output directory for generated documentation files
    env:
      HTML_DIR: 'docs/_build/html'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Setup build environment
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Setup Syphinx
      run: pip install -U 'sphinx<1.8' sphinx_rtd_theme sphinxcontrib-versioning

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Builds the documentation for all branches and tags
    - name: Build Documentation
      run: echo $HTML_DIR && sphinx-versioning build -w master docs $HTML_DIR && ls -la $HTML_DIR

    # Deploy to Github Pages
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.1
      with:
        # Build directory to deploy
        build_dir: $HTML_DIR
